using System;
using System.Collections.Generic;

namespace PhoneCodesListExample
{
    class Program
    {
        static void Main(string[] args)
        {
            
            var liste = new List<UlkeTelefon>(){
                new UlkeTelefon("Afghanistan","AF","+93"),
                new UlkeTelefon("Aland Islands","AX","+358"),
                new UlkeTelefon("Albania","AL","+355"),
                new UlkeTelefon("Algeria","DZ","+213"),
                new UlkeTelefon("AmericanSamoa","AS","+1684"),
                new UlkeTelefon("Andorra","AD","+376"),
                new UlkeTelefon("Angola","AO","+244"),
                new UlkeTelefon("Anguilla","AI","+1264"),
                new UlkeTelefon("Antarctica","AQ","+672"),
                new UlkeTelefon("Antigua and Barbuda","AG","+1268"),
                new UlkeTelefon("Argentina","AR","+54"),
                new UlkeTelefon("Armenia","AM","+374"),
                new UlkeTelefon("Aruba","AW","+297"),
                new UlkeTelefon("Australia","AU","+61"),
                new UlkeTelefon("Austria","AT","+43"),
                new UlkeTelefon("Azerbaijan","AZ","+994"),
                new UlkeTelefon("Bahamas","BS","+1242"),
                new UlkeTelefon("Bahrain","BH","+973"),
                new UlkeTelefon("Bangladesh","BD","+880"),
                new UlkeTelefon("Barbados","BB","+1246"),
                new UlkeTelefon("Belarus","BY","+375"),
                new UlkeTelefon("Belgium","BE","+32"),
                new UlkeTelefon("Belize","BZ","+501"),
                new UlkeTelefon("Benin","BJ","+229"),
                new UlkeTelefon("Bermuda","BM","+1441"),
                new UlkeTelefon("Bhutan","BT","+975"),
                new UlkeTelefon("Bolivia, Plurinational State of","BO","+591"),
                new UlkeTelefon("Bosnia and Herzegovina","BA","+387"),
                new UlkeTelefon("Botswana","BW","+267"),
                new UlkeTelefon("Brazil","BR","+55"),
                new UlkeTelefon("British Indian Ocean Territory","IO","+246"),
                new UlkeTelefon("Brunei Darussalam","BN","+673"),
                new UlkeTelefon("Bulgaria","BG","+359"),
                new UlkeTelefon("Burkina Faso","BF","+226"),
                new UlkeTelefon("Burundi","BI","+257"),
                new UlkeTelefon("Cambodia","KH","+855"),
                new UlkeTelefon("Cameroon","CM","+237"),
                new UlkeTelefon("Canada","CA","+1"),
                new UlkeTelefon("Cape Verde","CV","+238"),
                new UlkeTelefon("Cayman Islands","KY","+ 345"),
                new UlkeTelefon("Central African Republic","CF","+236"),
                new UlkeTelefon("Chad","TD","+235"),
                new UlkeTelefon("Chile","CL","+56"),
                new UlkeTelefon("China","CN","+86"),
                new UlkeTelefon("Christmas Island","CX","+61"),
                new UlkeTelefon("Cocos (Keeling) Islands","CC","+61"),
                new UlkeTelefon("Colombia","CO","+57"),
                new UlkeTelefon("Comoros","KM","+269"),
                new UlkeTelefon("Congo","CG","+242"),
                new UlkeTelefon("Congo, The Democratic Republic of the Congo","CD","+243"),
                new UlkeTelefon("Cook Islands","CK","+682"),
                new UlkeTelefon("Costa Rica","CR","+506"),
                new UlkeTelefon("Cote d'Ivoire","CI","+225"),
                new UlkeTelefon("Croatia","HR","+385"),
                new UlkeTelefon("Cuba","CU","+53"),
                new UlkeTelefon("Cyprus","CY","+357"),
                new UlkeTelefon("Czech Republic","CZ","+420"),
                new UlkeTelefon("Denmark","DK","+45"),
                new UlkeTelefon("Djibouti","DJ","+253"),
                new UlkeTelefon("Dominica","DM","+1767"),
                new UlkeTelefon("Dominican Republic","DO","+1849"),
                new UlkeTelefon("Ecuador","EC","+593"),
                new UlkeTelefon("Egypt","EG","+20"),
                new UlkeTelefon("El Salvador","SV","+503"),
                new UlkeTelefon("Equatorial Guinea","GQ","+240"),
                new UlkeTelefon("Eritrea","ER","+291"),
                new UlkeTelefon("Estonia","EE","+372"),
                new UlkeTelefon("Ethiopia","ET","+251"),
                new UlkeTelefon("Falkland Islands (Malvinas)","FK","+500"),
                new UlkeTelefon("Faroe Islands","FO","+298"),
                new UlkeTelefon("Fiji","FJ","+679"),
                new UlkeTelefon("Finland","FI","+358"),
                new UlkeTelefon("France","FR","+33"),
                new UlkeTelefon("French Guiana","GF","+594"),
                new UlkeTelefon("French Polynesia","PF","+689"),
                new UlkeTelefon("Gabon","GA","+241"),
                new UlkeTelefon("Gambia","GM","+220"),
                new UlkeTelefon("Georgia","GE","+995"),
                new UlkeTelefon("Germany","DE","+49"),
                new UlkeTelefon("Ghana","GH","+233"),
                new UlkeTelefon("Gibraltar","GI","+350"),
                new UlkeTelefon("Greece","GR","+30"),
                new UlkeTelefon("Greenland","GL","+299"),
                new UlkeTelefon("Grenada","GD","+1473"),
                new UlkeTelefon("Guadeloupe","GP","+590"),
                new UlkeTelefon("Guam","GU","+1671"),
                new UlkeTelefon("Guatemala","GT","+502"),
                new UlkeTelefon("Guernsey","GG","+44"),
                new UlkeTelefon("Guinea","GN","+224"),
                new UlkeTelefon("Guinea-Bissau","GW","+245"),
                new UlkeTelefon("Guyana","GY","+595"),
                new UlkeTelefon("Haiti","HT","+509"),
                new UlkeTelefon("Holy See (Vatican City State)","VA","+379"),
                new UlkeTelefon("Honduras","HN","+504"),
                new UlkeTelefon("Hong Kong","HK","+852"),
                new UlkeTelefon("Hungary","HU","+36"),
                new UlkeTelefon("Iceland","IS","+354"),
                new UlkeTelefon("India","IN","+91"),
                new UlkeTelefon("Indonesia","ID","+62"),
                new UlkeTelefon("Iran, Islamic Republic of Persian Gulf","IR","+98"),
                new UlkeTelefon("Iraq","IQ","+964"),
                new UlkeTelefon("Ireland","IE","+353"),
                new UlkeTelefon("Isle of Man","IM","+44"),
                new UlkeTelefon("Israel","IL","+972"),
                new UlkeTelefon("Italy","IT","+39"),
                new UlkeTelefon("Jamaica","JM","+1876"),
                new UlkeTelefon("Japan","JP","+81"),
                new UlkeTelefon("Jersey","JE","+44"),
                new UlkeTelefon("Jordan","JO","+962"),
                new UlkeTelefon("Kazakhstan","KZ","+77"),
                new UlkeTelefon("Kenya","KE","+254"),
                new UlkeTelefon("Kiribati","KI","+686"),
                new UlkeTelefon("Korea, Democratic People's Republic of Korea","KP","+850"),
                new UlkeTelefon("Korea, Republic of South Korea","KR","+82"),
                new UlkeTelefon("Kuwait","KW","+965"),
                new UlkeTelefon("Kyrgyzstan","KG","+996"),
                new UlkeTelefon("Laos","LA","+856"),
                new UlkeTelefon("Latvia","LV","+371"),
                new UlkeTelefon("Lebanon","LB","+961"),
                new UlkeTelefon("Lesotho","LS","+266"),
                new UlkeTelefon("Liberia","LR","+231"),
                new UlkeTelefon("Libyan Arab Jamahiriya","LY","+218"),
                new UlkeTelefon("Liechtenstein","LI","+423"),
                new UlkeTelefon("Lithuania","LT","+370"),
                new UlkeTelefon("Luxembourg","LU","+352"),
                new UlkeTelefon("Macao","MO","+853"),
                new UlkeTelefon("Macedonia","MK","+389"),
                new UlkeTelefon("Madagascar","MG","+261"),
                new UlkeTelefon("Malawi","MW","+265"),
                new UlkeTelefon("Malaysia","MY","+60"),
                new UlkeTelefon("Maldives","MV","+960"),
                new UlkeTelefon("Mali","ML","+223"),
                new UlkeTelefon("Malta","MT","+356"),
                new UlkeTelefon("Marshall Islands","MH","+692"),
                new UlkeTelefon("Martinique","MQ","+596"),
                new UlkeTelefon("Mauritania","MR","+222"),
                new UlkeTelefon("Mauritius","MU","+230"),
                new UlkeTelefon("Mayotte","YT","+262"),
                new UlkeTelefon("Mexico","MX","+52"),
                new UlkeTelefon("Micronesia, Federated States of Micronesia","FM","+691"),
                new UlkeTelefon("Moldova","MD","+373"),
                new UlkeTelefon("Monaco","MC","+377"),
                new UlkeTelefon("Mongolia","MN","+976"),
                new UlkeTelefon("Montenegro","ME","+382"),
                new UlkeTelefon("Montserrat","MS","+1664"),
                new UlkeTelefon("Morocco","MA","+212"),
                new UlkeTelefon("Mozambique","MZ","+258"),
                new UlkeTelefon("Myanmar","MM","+95"),
                new UlkeTelefon("Namibia","NA","+264"),
                new UlkeTelefon("Nauru","NR","+674"),
                new UlkeTelefon("Nepal","NP","+977"),
                new UlkeTelefon("Netherlands","NL","+31"),
                new UlkeTelefon("Netherlands Antilles","AN","+599"),
                new UlkeTelefon("New Caledonia","NC","+687"),
                new UlkeTelefon("New Zealand","NZ","+64"),
                new UlkeTelefon("Nicaragua","NI","+505"),
                new UlkeTelefon("Niger","NE","+227"),
                new UlkeTelefon("Nigeria","NG","+234"),
                new UlkeTelefon("Niue","NU","+683"),
                new UlkeTelefon("Norfolk Island","NF","+672"),
                new UlkeTelefon("Northern Mariana Islands","MP","+1670"),
                new UlkeTelefon("Norway","NO","+47"),
                new UlkeTelefon("Oman","OM","+968"),
                new UlkeTelefon("Pakistan","PK","+92"),
                new UlkeTelefon("Palau","PW","+680"),
                new UlkeTelefon("Palestinian Territory, Occupied","PS","+970"),
                new UlkeTelefon("Panama","PA","+507"),
                new UlkeTelefon("Papua New Guinea","PG","+675"),
                new UlkeTelefon("Paraguay","PY","+595"),
                new UlkeTelefon("Peru","PE","+51"),
                new UlkeTelefon("Philippines","PH","+63"),
                new UlkeTelefon("Pitcairn","PN","+872"),
                new UlkeTelefon("Poland","PL","+48"),
                new UlkeTelefon("Portugal","PT","+351"),
                new UlkeTelefon("Puerto Rico","PR","+1939"),
                new UlkeTelefon("Qatar","QA","+974"),
                new UlkeTelefon("Romania","RO","+40"),
                new UlkeTelefon("Russia","RU","+7"),
                new UlkeTelefon("Rwanda","RW","+250"),
                new UlkeTelefon("Reunion","RE","+262"),
                new UlkeTelefon("Saint Barthelemy","BL","+590"),
                new UlkeTelefon("Saint Helena, Ascension and Tristan Da Cunha","SH","+290"),
                new UlkeTelefon("Saint Kitts and Nevis","KN","+1869"),
                new UlkeTelefon("Saint Lucia","LC","+1758"),
                new UlkeTelefon("Saint Martin","MF","+590"),
                new UlkeTelefon("Saint Pierre and Miquelon","PM","+508"),
                new UlkeTelefon("Saint Vincent and the Grenadines","VC","+1784"),
                new UlkeTelefon("Samoa","WS","+685"),
                new UlkeTelefon("San Marino","SM","+378"),
                new UlkeTelefon("Sao Tome and Principe","ST","+239"),
                new UlkeTelefon("Saudi Arabia","SA","+966"),
                new UlkeTelefon("Senegal","SN","+221"),
                new UlkeTelefon("Serbia","RS","+381"),
                new UlkeTelefon("Seychelles","SC","+248"),
                new UlkeTelefon("Sierra Leone","SL","+232"),
                new UlkeTelefon("Singapore","SG","+65"),
                new UlkeTelefon("Slovakia","SK","+421"),
                new UlkeTelefon("Slovenia","SI","+386"),
                new UlkeTelefon("Solomon Islands","SB","+677"),
                new UlkeTelefon("Somalia","SO","+252"),
                new UlkeTelefon("South Africa","ZA","+27"),
                new UlkeTelefon("South Sudan","SS","+211"),
                new UlkeTelefon("South Georgia and the South Sandwich Islands","GS","+500"),
                new UlkeTelefon("Spain","ES","+34"),
                new UlkeTelefon("Sri Lanka","LK","+94"),
                new UlkeTelefon("Sudan","SD","+249"),
                new UlkeTelefon("Suriname","SR","+597"),
                new UlkeTelefon("Svalbard and Jan Mayen","SJ","+47"),
                new UlkeTelefon("Swaziland","SZ","+268"),
                new UlkeTelefon("Sweden","SE","+46"),
                new UlkeTelefon("Switzerland","CH","+41"),
                new UlkeTelefon("Syrian Arab Republic","SY","+963"),
                new UlkeTelefon("Taiwan","TW","+886"),
                new UlkeTelefon("Tajikistan","TJ","+992"),
                new UlkeTelefon("Tanzania, United Republic of Tanzania","TZ","+255"),
                new UlkeTelefon("Thailand","TH","+66"),
                new UlkeTelefon("Timor-Leste","TL","+670"),
                new UlkeTelefon("Togo","TG","+228"),
                new UlkeTelefon("Tokelau","TK","+690"),
                new UlkeTelefon("Tonga","TO","+676"),
                new UlkeTelefon("Trinidad and Tobago","TT","+1868"),
                new UlkeTelefon("Tunisia","TN","+216"),
                new UlkeTelefon("Turkey","TR","+90"),
                new UlkeTelefon("Turkmenistan","TM","+993"),
                new UlkeTelefon("Turks and Caicos Islands","TC","+1649"),
                new UlkeTelefon("Tuvalu","TV","+688"),
                new UlkeTelefon("Uganda","UG","+256"),
                new UlkeTelefon("Ukraine","UA","+380"),
                new UlkeTelefon("United Arab Emirates","AE","+971"),
                new UlkeTelefon("United Kingdom","GB","+44"),
                new UlkeTelefon("United States","US","+1"),
                new UlkeTelefon("Uruguay","UY","+598"),
                new UlkeTelefon("Uzbekistan","UZ","+998"),
                new UlkeTelefon("Vanuatu","VU","+678"),
                new UlkeTelefon("Venezuela, Bolivarian Republic of Venezuela","VE","+58"),
                new UlkeTelefon("Vietnam","VN","+84"),
                new UlkeTelefon("Virgin Islands, British","VG","+1284"),
                new UlkeTelefon("Virgin Islands, U.S.","VI","+1340"),
                new UlkeTelefon("Wallis and Futuna","WF","+681"),
                new UlkeTelefon("Yemen","YE","+967"),
                new UlkeTelefon("Zambia","ZM","+260"),
                new UlkeTelefon("Zimbabwe","ZW","+263"),
            };
        }
    }

    public class UlkeTelefon{
        public UlkeTelefon(string u, string c, string p){
            Ulke = u;
            Code = c;
            PhoneCode = p;
        }
        public string Ulke{get;set;}
        public string Code{get;set;}
        public string PhoneCode{get;set;}
    }
}